### PR TITLE
Koi utils

### PR DESCRIPTION
**Pull request by Salman-Arshad**

### CODE REVIEW

**Comment by AndreVallestero** [comment]
I will test and merge this once bundler is working. Note, version must be bumped to beta.22.

**Comment by Salman-Arshad** [comment]
Okay I wll bump it now!

**Comment by AndreVallestero** [comment]
Is there a reason we can't have this in `common.ts`?

**Comment by Salman-Arshad** [comment]
> Is there a reason we can't have this in `common.ts`?

Yes because these functions do not require the wallet to be initialized and are independent of the wallet.

**Comment by AndreVallestero** [comment]
> Yes because these functions do not require the wallet to be initialized and are independent of the wallet, so a separate class for the utils will make things more bug and stress-free for the community

We can put it in `Common` just like how [`getCacheData`](https://github.com/open-koi/tools/blob/main/src/common.ts#L508) and [`getArweaveNetInfo`](https://github.com/open-koi/tools/blob/main/src/common.ts#L516) are in common and don't require the wallet to be initialized.

**Comment by Salman-Arshad** [comment]
Ahan, I see. Please close this PR

**Pull request closed without merging**
